apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turin-platform-audit-pvc
  namespace: {{ .Values.namespace | default "turin-platform" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
